name: Snyk Scan
on: [push, pull_request]
jobs:
  snyk-scan-python:
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'  # o la versi√≥n que uses en tu proyecto

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Snyk CLI
        run: |
          curl -sL https://github.com/snyk/snyk/releases/download/v1.842.0/snyk-linux-x64-1.842.0.tar.gz | tar xz
          sudo mv snyk /usr/local/bin

      - name: Run Snyk test
        run: snyk test --all-projects


  snyk-scan-node:
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: cd ./snyk/javascripts && npm install

      - name: Install Snyk
        run: npm install -g snyk

      - name: Run Snyk to check for vulnerabilities
        run: cd ./snyk/javascripts && snyk test

  snyk-scan-java:
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: cd ./snyk/java && npm install

      - name: Install Snyk
        run: npm install -g snyk

      - name: Run Snyk to check for vulnerabilities
        run: cd ./snyk/java && snyk test

